var podradio=angular.module("podradio",["ionic","ngCordova"]).run(function(a,b){a.ready(function(){window.cordova&&window.cordova.plugins.Keyboard&&cordova.plugins.Keyboard.hideKeyboardAccessoryBar(!0);window.StatusBar&&StatusBar.styleDefault();localStorage.getItem("downloads")||localStorage.setItem("downloads",JSON.stringify([]));localStorage.getItem("registrationID")?b.go("home"):b.go("register")})});
podradio.config(function(a){a.state("prototype",{templateUrl:"templates/prototype.html",controller:"AudioCtrl"}).state("register",{templateUrl:"templates/register.html",controller:"RegisterCtrl"}).state("home",{templateUrl:"templates/home.html",controller:"HomeCtrl",cache:!1}).state("region",{templateUrl:"templates/region.html",controller:"RegionCtrl"}).state("school",{templateUrl:"templates/school.html",controller:"SchoolCtrl",params:{region_id:null,region_name:null}}).state("podcast",{templateUrl:"templates/podcast.html",
controller:"PodcastCtrl",params:{school_id:null,school_name:null},cache:!1}).state("player",{templateUrl:"templates/player.html",controller:"PlayerCtrl",params:{podcast:null,downloaded:null},cache:!1}).state("saved",{templateUrl:"templates/saved.html",controller:"SavedCtrl"})});
podradio.controller("RegisterCtrl",function(a,b,c,d){a.loading=!1;a.invalidEmail=!1;a.data={};localStorage.getItem("subscribed")?"no"==localStorage.getItem("subscribed")?a.data.subscribed=!1:a.data.subscribed=!0:a.data.subscribed=!0;a.register=function(){a.loading=!0;var c=a.data.name,f=a.data.email,e=a.data.subscribed?"yes":"no";localStorage.setItem("subscribed",e);/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i.test(f)?d({method:"POST",url:global_url+"/api/register",
data:"name="+c+"&email="+f+"&subscribed="+e,headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(c){localStorage.setItem("registrationID",c.data.registration_id);a.loading=!1;b.go("home")},function(c){a.loading=!1;b.go("home")}):(a.invalidEmail=!0,a.loading=!1)};a.infoModal=function(b){a.podcast=b;c.fromTemplateUrl("templates/register-info-modal.html",{scope:a,animation:"slide-in-up"}).then(function(b){a.modal=b;a.modal.show()})};a.closeModal=function(){a.modal&&a.modal.hide()};
a.$on("$destroy",function(){a.modal.remove()});a.$on("modal.hidden",function(){});a.$on("modal.removed",function(){})});podradio.controller("HomeCtrl",function(a,b,c,d){c.clearHistory();d.showBackButton(!1);a.browse=function(){b.go("region")};a.savedPodcasts=function(){b.go("saved")}});
podradio.controller("SavedCtrl",function(a,b,c,d,g){g.showBackButton(!0);a.downloads=JSON.parse(localStorage.getItem("downloads"));a.player=function(a,c){a.downloaded=c;b.go("player",{podcast:a,downloaded:c})};a.infoModal=function(b){a.podcast=b;d.fromTemplateUrl("templates/info-modal.html",{scope:a,animation:"slide-in-up"}).then(function(b){a.modal=b;a.modal.show()})};a.closeModal=function(){a.modal&&a.modal.hide()};a.$on("$destroy",function(){a.modal&&a.modal.remove()});a.$on("modal.hidden",function(){});
a.$on("modal.removed",function(){});a["delete"]=function(b){c.show({template:"<ion-spinner></ion-spinner>"});window.requestFileSystem(LocalFileSystem.PERSISTENT,0,function(e){a.podFile=null;e.root.getDirectory("PodradioDownloads",{create:!0},function(e){e.getFile(b,{create:!0,exclusive:!1},function(e){var d=e.toURL();a.filePath=d;e.remove();e=JSON.parse(localStorage.getItem("downloads"));for(d=0;d<e.length;d++)e[d].file_name==b&&e.splice(d,1);localStorage.setItem("downloads",JSON.stringify(e));a.downloads=
e;a.$apply();c.hide()},function(a){c.hide()})})},function(a){c.hide()})}});podradio.controller("RegionCtrl",function(a,b,c,d){d.showBackButton(!0);a.regions=null;c.get_region_list(a);a.school=function(a,c){b.go("school",{region_id:a,region_name:c})}});podradio.controller("SchoolCtrl",function(a,b,c,d,g){g.showBackButton(!0);a.schools=null;g=d.region_id;a.region_name=d.region_name;c.get_school_list(a,g);a.podcast=function(a,c){b.go("podcast",{school_id:a,school_name:c})}});
podradio.controller("PodcastCtrl",function(a,b,c,d,g,f,e,h){h.showBackButton(!0);a.podcasts=null;var l=d.school_id;a.school_name=d.school_name;c.get_school_podcasts(a,l,null);a.more_podcasts=function(b){console.log("CURSOR: ",b);c.get_school_podcasts(a,l,b)};a.player=function(a,c){b.go("player",{podcast:a,downloaded:c})};a.infoModal=function(b){a.podcast=b;g.fromTemplateUrl("templates/info-modal.html",{scope:a,animation:"slide-in-up"}).then(function(b){a.modal=b;a.modal.show()})};a.closeModal=function(){a.modal&&
a.modal.hide()};a.$on("$destroy",function(){a.modal&&a.modal.remove()});a.$on("modal.hidden",function(){});a.$on("modal.removed",function(){});a.download=function(b,d,g,f){a.podcast=f;e.show({template:"<ion-spinner></ion-spinner><br>Downloading to Saved Podcasts"});window.requestFileSystem(LocalFileSystem.PERSISTENT,0,function(f){a.podFile=null;f.root.getDirectory("PodradioDownloads",{create:!0},function(f){f.getFile(d,{create:!0,exclusive:!1},function(f){var h=f.toInternalURL();a.filePath=h;f.remove();
ft=new FileTransfer;ft.download(encodeURI(b),h,function(k){e.hide();a.podFile=k.toInternalURL();k=JSON.parse(localStorage.getItem("downloads"));k.push({download_link:b,file_name:d,category:g,file_path:a.podFile,podcast:a.podcast});localStorage.setItem("downloads",JSON.stringify(k));a.downloads=k;for(k=0;k<a.podcasts.length;k++)a.podcasts[k].id===a.podcast.id&&(a.podcasts[k].downloaded=a.podFile);try{c.track_download(a.podcast.id)}catch(w){console.log("error: ",w)}a.$apply()},function(a){console.log(a);
e.hide()},!1,null)},function(){e.hide()})})},function(){e.hide()})}});
podradio.controller("PlayerCtrl",function(a,b,c,d,g,f,e,h,l,r){function t(b){1!=b&&(a.loading="not loading",e.hide());a.$apply()}function u(){}function v(a){}function p(a){var b=Math.floor(a/60);a=Math.floor(a-60*b);0>b&&(b=0);0>a&&(a=0);b=b.toString();a=a.toString();2>b.length&&(b="0"+b);2>a.length&&(a="0"+a);return b+":"+a}r.showBackButton(!0);a.media=null;a.podcast=g.podcast;a.downloaded=g.downloaded;c.get_in_app_message(a);a.$on("$ionicView.beforeLeave",function(){a.stop()});a.data={backgroundMode:!0,
progress:0};a.toggleBackgroundMode=function(){cordova.plugins.backgroundMode.isEnabled()&&!a.data.backgroundMode&&cordova.plugins.backgroundMode.disable();!cordova.plugins.backgroundMode.isEnabled()&&a.data.backgroundMode&&(cordova.plugins.backgroundMode.setDefaults({text:"Tap to go back to Podradio"}),cordova.plugins.backgroundMode.enable())};a.seeking=!1;var m=null;a.$watch("data.progress",function(){null===m&&(m=d(function(){d.cancel(m);m=null},1E3))});a.touched_seek=function(){a.seeking=!0};a.released_seek=
function(){0<a.dur&&a.media?a.media.seekTo(Math.floor(a.data.progress*a.dur*1E3/100)):a.data.progress=0;a.seeking=!1};a.share=function(a,b){h.share(a,"Podradio",null,b)};a.media=null;a.loading="not loading";a.duration="00:00";a.dur=0;a.mediaPosition="00:00";a.mediaPositionPerc=0;var q=null,n=0;a.stop=function(){cordova.plugins.backgroundMode.disable();a.playing=!1;a.media&&a.media.stop();a.media=null;a.data.progress=0;a.mediaPosition="00:00";a.media.release()};a.pause=function(){cordova.plugins.backgroundMode.disable();
a.playing=!1;a.media.pause()};cordova.plugins.backgroundMode.isEnabled()&&(cordova.plugins.backgroundMode.onactivate=function(){a.playing&&a.data.backgroundMode?a.media.play():(a.playing=!1,a.media.pause())});a.play=function(b){a.playing=!0;a.data.backgroundMode&&(cordova.plugins.backgroundMode.setDefaults({text:"Tap to go back to Podradio"}),cordova.plugins.backgroundMode.enable());a.loading="loading...";e.show({template:"<ion-spinner></ion-spinner>"});setTimeout(function(){if(a.media)a.media.play();
else{a.media=new Media(b,u,v,t);n=0;q=setInterval(function(){n+=100;1E4<n&&clearInterval(q);var b=a.media.getDuration();0<b&&(clearInterval(q),a.duration=p(b),a.dur=b,a.$apply())},100);a.media.play({playAudioWhenScreenIsLocked:!0});try{c.track_play(a.podcast.id)}catch(e){console.log("tracking error error error: ",e)}}},300);setInterval(function(){a.media.getCurrentPosition(function(b){-1<b?(a.mediaPosition=p(b),a.mediaPositionPerc=Math.floor(b/a.media.getDuration()*100),a.seeking||(a.data={progress:a.mediaPositionPerc,
backgroundMode:a.data.backgroundMode},b>=a.dur&&(a.data={progress:0,backgroundMode:!1},a.stop())),a.$apply()):(a.mediaPosition=p(0),a.mediaPositionPerc=0)},function(a){console.log("Error getting pos="+a)})},1E3)};a.goHome=function(){b.go("home")};a.savedPodcasts=function(){b.go("saved")};a.download=function(b,d,g){e.show({template:"<ion-spinner></ion-spinner><br>Downloading to Saved Podcasts"});window.requestFileSystem(LocalFileSystem.PERSISTENT,0,function(f){a.podFile=null;f.root.getDirectory("PodradioDownloads",
{create:!0},function(f){f.getFile(d,{create:!0,exclusive:!1},function(f){var h=f.toInternalURL();a.filePath=h;f.remove();ft=new FileTransfer;ft.download(encodeURI(b),h,function(f){e.hide();a.podFile=f.toInternalURL();f=JSON.parse(localStorage.getItem("downloads"));f.push({download_link:b,file_name:d,category:g,file_path:a.podFile,podcast:a.podcast});localStorage.setItem("downloads",JSON.stringify(f));a.downloads=f;a.podcast.downloaded=a.podFile;a.$apply();try{c.track_download(a.podcast.id)}catch(h){console.log("error: ",
h)}},function(a){console.log(a);e.hide()},!1,null)},function(){e.hide();console.log("Get file failed")})})},function(){e.hide();console.log("Request for filesystem failed")})};l.fromTemplateUrl("templates/join-mailer-modal.html",{scope:a,animation:"slide-in-up"}).then(function(b){a.modal=b});a.openModal=function(){a.modal.show()};a.closeModal=function(){a.modal&&a.modal.hide()};a.$on("$destroy",function(){a.modal.remove()});a.$on("modal.hidden",function(){});a.$on("modal.removed",function(){});a.openSponsorLink=
function(a){window.open(a,"_system","location=yes")}});
podradio.factory("api",function(a){return{get_region_list:function(b){a.get(global_url+"/api/get_region_list").then(function(a){b.regions=a.data},function(a){$scope_var=null})},get_school_list:function(b,c){a.get(global_url+"/api/get_school_list/"+c).then(function(a){b.schools=a.data},function(a){b.schools=null})},get_school_podcasts:function(b,c,d){d||(d="");a.get(global_url+"/api/get_school_podcasts/"+c+"?cursor="+d).then(function(a){console.log("podcast list response: ",a.data);if(localStorage.getItem("downloads"))for(var c=
JSON.parse(localStorage.getItem("downloads")),e=0;e<a.data.podcasts.length;e++){a.data.podcasts[e].downloaded=!1;for(var d=0;d<c.length;d++)a.data.podcasts[e].id==c[d].podcast.id&&(a.data.podcasts[e].downloaded=c[d].file_path)}b.podcasts=a.data.podcasts;b.next_curs=a.data.next_curs;console.log("API next_curs: ",b.next_curs)},function(a){b.podcasts=null})},get_all_podcasts:function(){},get_in_app_message:function(b){a.get(global_url+"/api/get_message?podcast_id="+b.podcast.id).then(function(a){b.inAppMessage=
a.data.message;b.sponsorLink=a.data.link;b.sponsorImage=a.data.image},function(a){b.inAppMessage=null;b.sponsorLink=!1;b.sponsorImage=!1})},track_download:function(b){a({method:"POST",url:global_url+"/api/track_download",data:"key=podRadioyo&podcast_id="+b,headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(a){},function(a){})},track_play:function(b){a({method:"POST",url:global_url+"/api/track_play",data:"key=podRadioyo&podcast_id="+b,headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(a){},
function(a){})}}});