var podradio=angular.module("controllers",[]);
podradio.controller("RegisterCtrl",function(a,c,b,d){a.loading=!1;a.invalidEmail=!1;a.data={};localStorage.getItem("subscribed")?"no"==localStorage.getItem("subscribed")?a.data.subscribed=!1:a.data.subscribed=!0:a.data.subscribed=!0;a.register=function(){a.loading=!0;var b=a.data.name,f=a.data.email,e=a.data.subscribed?"yes":"no";localStorage.setItem("subscribed",e);/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i.test(f)?d({method:"POST",url:global_url+"/api/register",
data:"name="+b+"&email="+f+"&subscribed="+e,headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(b){localStorage.setItem("registrationID",b.data.registration_id);a.loading=!1;c.go("home")},function(b){a.loading=!1;c.go("home")}):(a.invalidEmail=!0,a.loading=!1)};a.infoModal=function(c){a.podcast=c;b.fromTemplateUrl("templates/register-info-modal.html",{scope:a,animation:"slide-in-up"}).then(function(b){a.modal=b;a.modal.show()})};a.closeModal=function(){a.modal&&a.modal.hide()};
a.$on("$destroy",function(){a.modal.remove()});a.$on("modal.hidden",function(){});a.$on("modal.removed",function(){})});podradio.controller("HomeCtrl",function(a,c,b,d){b.clearHistory();d.showBackButton(!1);a.browse=function(){c.go("region")};a.savedPodcasts=function(){c.go("saved")}});
podradio.controller("SavedCtrl",function(a,c,b,d,g){g.showBackButton(!0);a.downloads=JSON.parse(localStorage.getItem("downloads"));a.player=function(a,b){a.downloaded=b;c.go("player",{podcast:a,downloaded:b})};a.infoModal=function(b){a.podcast=b;d.fromTemplateUrl("templates/info-modal.html",{scope:a,animation:"slide-in-up"}).then(function(b){a.modal=b;a.modal.show()})};a.closeModal=function(){a.modal&&a.modal.hide()};a.$on("$destroy",function(){a.modal&&a.modal.remove()});a.$on("modal.hidden",function(){});
a.$on("modal.removed",function(){});a["delete"]=function(c){b.show({template:"<ion-spinner></ion-spinner>"});window.requestFileSystem(LocalFileSystem.PERSISTENT,0,function(e){a.podFile=null;e.root.getDirectory("PodradioDownloads",{create:!0},function(e){e.getFile(c,{create:!0,exclusive:!1},function(e){var d=e.toURL();a.filePath=d;e.remove();e=JSON.parse(localStorage.getItem("downloads"));for(d=0;d<e.length;d++)e[d].file_name==c&&e.splice(d,1);localStorage.setItem("downloads",JSON.stringify(e));a.downloads=
e;a.$apply();b.hide()},function(a){b.hide()})})},function(a){b.hide()})}});podradio.controller("RegionCtrl",function(a,c,b,d){d.showBackButton(!0);a.regions=null;b.get_region_list(a);a.school=function(a,b){c.go("school",{region_id:a,region_name:b})}});podradio.controller("SchoolCtrl",function(a,c,b,d,g){g.showBackButton(!0);a.schools=null;g=d.region_id;a.region_name=d.region_name;b.get_school_list(a,g);a.podcast=function(a,b){c.go("podcast",{school_id:a,school_name:b})}});
podradio.controller("PodcastCtrl",function(a,c,b,d,g,f,e,h){h.showBackButton(!0);a.podcasts=null;var l=d.school_id;a.school_name=d.school_name;b.get_school_podcasts(a,l,null);a.more_podcasts=function(c){console.log("CURSOR: ",c);b.get_school_podcasts(a,l,c)};a.player=function(a,b){c.go("player",{podcast:a,downloaded:b})};a.infoModal=function(b){a.podcast=b;g.fromTemplateUrl("templates/info-modal.html",{scope:a,animation:"slide-in-up"}).then(function(b){a.modal=b;a.modal.show()})};a.closeModal=function(){a.modal&&
a.modal.hide()};a.$on("$destroy",function(){a.modal&&a.modal.remove()});a.$on("modal.hidden",function(){});a.$on("modal.removed",function(){});a.download=function(c,d,g,f){a.podcast=f;e.show({template:"<ion-spinner></ion-spinner><br>Downloading to Saved Podcasts"});window.requestFileSystem(LocalFileSystem.PERSISTENT,0,function(f){a.podFile=null;f.root.getDirectory("PodradioDownloads",{create:!0},function(f){f.getFile(d,{create:!0,exclusive:!1},function(f){var h=f.toInternalURL();a.filePath=h;f.remove();
ft=new FileTransfer;ft.download(encodeURI(c),h,function(k){e.hide();a.podFile=k.toInternalURL();k=JSON.parse(localStorage.getItem("downloads"));k.push({download_link:c,file_name:d,category:g,file_path:a.podFile,podcast:a.podcast});localStorage.setItem("downloads",JSON.stringify(k));a.downloads=k;for(k=0;k<a.podcasts.length;k++)a.podcasts[k].id===a.podcast.id&&(a.podcasts[k].downloaded=a.podFile);try{b.track_download(a.podcast.id)}catch(w){console.log("error: ",w)}a.$apply()},function(a){console.log(a);
e.hide()},!1,null)},function(){e.hide()})})},function(){e.hide()})}});
podradio.controller("PlayerCtrl",function(a,c,b,d,g,f,e,h,l,r){function t(b){1!=b&&(a.loading="not loading",e.hide());a.$apply()}function u(){}function v(a){}function p(a){var b=Math.floor(a/60);a=Math.floor(a-60*b);0>b&&(b=0);0>a&&(a=0);b=b.toString();a=a.toString();2>b.length&&(b="0"+b);2>a.length&&(a="0"+a);return b+":"+a}r.showBackButton(!0);a.media=null;a.podcast=g.podcast;a.downloaded=g.downloaded;b.get_in_app_message(a);a.$on("$ionicView.beforeLeave",function(){a.stop()});a.data={backgroundMode:!0,
progress:0};a.toggleBackgroundMode=function(){cordova.plugins.backgroundMode.isEnabled()&&!a.data.backgroundMode&&cordova.plugins.backgroundMode.disable();!cordova.plugins.backgroundMode.isEnabled()&&a.data.backgroundMode&&(cordova.plugins.backgroundMode.setDefaults({text:"Tap to go back to Podradio"}),cordova.plugins.backgroundMode.enable())};a.seeking=!1;var m=null;a.$watch("data.progress",function(){null===m&&(m=d(function(){d.cancel(m);m=null},1E3))});a.touched_seek=function(){a.seeking=!0};a.released_seek=
function(){0<a.dur&&a.media?a.media.seekTo(Math.floor(a.data.progress*a.dur*1E3/100)):a.data.progress=0;a.seeking=!1};a.share=function(a,b){h.share(a,"Podradio",null,b)};a.media=null;a.loading="not loading";a.duration="00:00";a.dur=0;a.mediaPosition="00:00";a.mediaPositionPerc=0;var q=null,n=0;a.stop=function(){cordova.plugins.backgroundMode.disable();a.playing=!1;a.media&&a.media.stop();a.media=null;a.data.progress=0;a.mediaPosition="00:00";a.media.release()};a.pause=function(){cordova.plugins.backgroundMode.disable();
a.playing=!1;a.media.pause()};cordova.plugins.backgroundMode.isEnabled()&&(cordova.plugins.backgroundMode.onactivate=function(){a.playing&&a.data.backgroundMode?a.media.play():(a.playing=!1,a.media.pause())});a.play=function(c){a.playing=!0;a.data.backgroundMode&&(cordova.plugins.backgroundMode.setDefaults({text:"Tap to go back to Podradio"}),cordova.plugins.backgroundMode.enable());a.loading="loading...";e.show({template:"<ion-spinner></ion-spinner>"});setTimeout(function(){if(a.media)a.media.play();
else{a.media=new Media(c,u,v,t);n=0;q=setInterval(function(){n+=100;1E4<n&&clearInterval(q);var b=a.media.getDuration();0<b&&(clearInterval(q),a.duration=p(b),a.dur=b,a.$apply())},100);a.media.play({playAudioWhenScreenIsLocked:!0});try{b.track_play(a.podcast.id)}catch(e){console.log("tracking error error error: ",e)}}},300);setInterval(function(){a.media.getCurrentPosition(function(b){-1<b?(a.mediaPosition=p(b),a.mediaPositionPerc=Math.floor(b/a.media.getDuration()*100),a.seeking||(a.data={progress:a.mediaPositionPerc,
backgroundMode:a.data.backgroundMode},b>=a.dur&&(a.data={progress:0,backgroundMode:!1},a.stop())),a.$apply()):(a.mediaPosition=p(0),a.mediaPositionPerc=0)},function(a){console.log("Error getting pos="+a)})},1E3)};a.goHome=function(){c.go("home")};a.savedPodcasts=function(){c.go("saved")};a.download=function(c,d,g){e.show({template:"<ion-spinner></ion-spinner><br>Downloading to Saved Podcasts"});window.requestFileSystem(LocalFileSystem.PERSISTENT,0,function(f){a.podFile=null;f.root.getDirectory("PodradioDownloads",
{create:!0},function(f){f.getFile(d,{create:!0,exclusive:!1},function(f){var h=f.toInternalURL();a.filePath=h;f.remove();ft=new FileTransfer;ft.download(encodeURI(c),h,function(f){e.hide();a.podFile=f.toInternalURL();f=JSON.parse(localStorage.getItem("downloads"));f.push({download_link:c,file_name:d,category:g,file_path:a.podFile,podcast:a.podcast});localStorage.setItem("downloads",JSON.stringify(f));a.downloads=f;a.podcast.downloaded=a.podFile;a.$apply();try{b.track_download(a.podcast.id)}catch(h){console.log("error: ",
h)}},function(a){console.log(a);e.hide()},!1,null)},function(){e.hide();console.log("Get file failed")})})},function(){e.hide();console.log("Request for filesystem failed")})};l.fromTemplateUrl("templates/join-mailer-modal.html",{scope:a,animation:"slide-in-up"}).then(function(b){a.modal=b});a.openModal=function(){a.modal.show()};a.closeModal=function(){a.modal&&a.modal.hide()};a.$on("$destroy",function(){a.modal.remove()});a.$on("modal.hidden",function(){});a.$on("modal.removed",function(){});a.openSponsorLink=
function(a){window.open(a,"_system","location=yes")}});
podradio.factory("api",function(a){return{get_region_list:function(c){a.get(global_url+"/api/get_region_list").then(function(a){c.regions=a.data},function(a){$scope_var=null})},get_school_list:function(c,b){a.get(global_url+"/api/get_school_list/"+b).then(function(a){c.schools=a.data},function(a){c.schools=null})},get_school_podcasts:function(c,b,d){d||(d="");a.get(global_url+"/api/get_school_podcasts/"+b+"?cursor="+d).then(function(a){console.log("podcast list response: ",a.data);if(localStorage.getItem("downloads"))for(var b=
JSON.parse(localStorage.getItem("downloads")),e=0;e<a.data.podcasts.length;e++){a.data.podcasts[e].downloaded=!1;for(var d=0;d<b.length;d++)a.data.podcasts[e].id==b[d].podcast.id&&(a.data.podcasts[e].downloaded=b[d].file_path)}c.podcasts=a.data.podcasts;c.next_curs=a.data.next_curs;console.log("API next_curs: ",c.next_curs)},function(a){c.podcasts=null})},get_all_podcasts:function(){},get_in_app_message:function(c){a.get(global_url+"/api/get_message?podcast_id="+c.podcast.id).then(function(a){c.inAppMessage=
a.data.message;c.sponsorLink=a.data.link;c.sponsorImage=a.data.image},function(a){c.inAppMessage=null;c.sponsorLink=!1;c.sponsorImage=!1})},track_download:function(c){a({method:"POST",url:global_url+"/api/track_download",data:"key=podRadioyo&podcast_id="+c,headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(a){},function(a){})},track_play:function(c){a({method:"POST",url:global_url+"/api/track_play",data:"key=podRadioyo&podcast_id="+c,headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(a){},
function(a){})}}});